application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      GatsbyToMark:
        license: Apache-2.0
        actions:
          generic:
            function: dist/index.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
