application:
  hooks:
    pre-app-build: npm run build
  runtimeManifest:
    packages:
      md2markup:
        license: Apache-2.0
        actions:
          main:
            function: dist/index.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
